services:
  - type: web
    name: multi-llm-chat-prod
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: starter
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_WEB_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
